//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajtszám;Kategória;Név;Egyesület;Idő
        ///M107;m3f;Ács Zoltán;;1:21:25
        ///M15;fn;Adámi Krisztina;ÁkosBike Team Aszód;1:14:46
        ///R38;m2f;Adamkó Gergely;;1:58:10
        ///K214;ff;Ádók Róbert;;3:58:51
        ///R320;m1f;Almádi László;;2:13:13
        ///R376;m2f;Andreyev Kostyantyn;;1:45:23
        ///R180;m2f;Andrusch István;PCCC;1:42:14
        ///M115;ff;Angyal Zsolt;;1:10:24
        ///R256;m3f;Attila Pintér;;2:29:17
        ///K110;m2f;Bagi Csaba;;3:31:29
        ///K190;m1f;Bahul József;Ózdi Kerékpáros Egyesület;2:50:00
        ///K218;m2f;Bakocs Péter;;3:57:37
        ///R206;m2n;Bakonyi Györgyi;Vegan Ener [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bukkm2019 {
            get {
                return ResourceManager.GetString("bukkm2019", resourceCulture);
            }
        }
    }
}
